create table if not exists public.payments (
 id bigint generated by default as identity primary key,
 order_id text unique not null,
 name text not null,
 email text not null,
 amount integer not null default 50000,
 method text not null default 'KPay',
 slip_path text not null,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 certificate_id text,
 created_at timestamptz not null default now(),
 approved_at timestamptz
);

alter table public.payments enable row level security;

-- Public users may INSERT only. They cannot read/update payments.
create policy "public can submit payment"
on public.payments for insert
to anon
with check (amount = 50000 and status = 'pending');

-- Create a Storage bucket named payment-slips in the Supabase dashboard.
-- For the first test, allow anon uploads to that bucket.
-- Before production, replace this with a strict upload policy and file-size/type restrictions.
